version: '3.8'

# Define the services
# Op-adapter connects to Yente (OpenSanctions) API
# Yente uses Elasticsearch as its data store
services:
  op-adapter:
    build: ./op-adapter
    ports:
      - "3001:3000"           
    environment:
      - YENTE_API_URL=http://yente:8000
    depends_on:
      yente:
        condition: service_started

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3000" # Wystawiamy na porcie 3002
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth_db
      - JWT_SECRET=super_tajny_klucz_do_prototypu_123
    depends_on:
      - mongo

  # OpenSanctions (Yente)
  yente:
    image: ghcr.io/opensanctions/yente:5.1.0
    ports:
      - "8000:8000"
    environment:
      - YENTE_TITLE=Local Compliance API
      # "default" the full OpenSanctions dataset
      # "us_ofac_sdn" the US main sanctions list
      - YENTE_MANIFEST=/manifest.yml
      # Use local Elasticsearch instance (local)
      - YENTE_ELASTICSEARCH_URL=http://elasticsearch:9200
      # Automatic data update on startup
      - YENTE_UPDATE_DATA=true     
    volumes:
      # Saving downloaded data to disk
      - yente_data:/data
      # Mounting the manifest file
      - ./manifest.yml:/manifest.yml
    depends_on:
      elasticsearch:
        condition: service_healthy # Ensure ES is healthy before starting Yente
    deploy:
      resources:
        limits:
          memory: 4G

  # Data Base
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity
      - ES_JAVA_OPTS=-Xms1g -Xmx1g # Limit Java to 1GB RAM
    ports:
      - "9200:9200" # Elasticsearch REST API for debugging
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G

    # Check Elasticsearch health
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 12


  # --- 3. BAZY DANYCH APLIKACJI ---
  # Baza dla Auth Service (UÅ¼ytkownicy)
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Baza dla Core Service (Logi/Historia)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=core_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  yente_data:
  es_data:
  mongo_data:
  postgres_data: