version: '3.8'

# Define the services
# Op-adapter connects to Yente (OpenSanctions) API
# Yente uses Elasticsearch as its data store
services:
  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway/logs:/app/logs
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      - PORT=8080
      # URLs for downstream services
      - AUTH_SERVICE_URL=http://auth-service:3000
      - OP_ADAPTER_URL=http://op-adapter:3000
      - JWT_SECRET=${JWT_SECRET}
      - CORE_SERVICE_URL=http://core-service:3000
    depends_on:
      - auth-service
      - op-adapter

  frontend:
    build: ./frontend
    container_name: ${FRONTEND_CONTAINER_NAME}
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080 
    depends_on:
      - api-gateway
    networks:
      - default
  op-adapter:
    build: ./op-adapter
    # For testing purposes, delete comments below to expose port
    #ports:
    #  - "3001:3000"   
    volumes:
      - ./op-adapter/logs:/app/logs        
    environment:
      - YENTE_API_URL=http://yente:${YENTE_PORT}
    depends_on:
      yente:
        condition: service_started

  auth-service:
    build: ./auth-service
    # For testing purposes, delete comments below to expose port
    #ports:
    #  - "${PORT_AUTH}:3000"
    volumes:
      - ./auth-service/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      # Ethernal config for email sending
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      # Frontend URL for password reset links
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongo

  core-service:
    build: ./core-service
    # For testing purposes, delete comments below to expose port
    #ports:
    #  - "3005:3000" # External access on port 3005 (for debugging)
    volumes:
      - ./core-service/logs:/app/logs
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - OP_ADAPTER_URL=http://op-adapter:3000
    depends_on:
      - postgres
      - op-adapter

  # OpenSanctions (Yente)
  yente:
    image: ghcr.io/opensanctions/yente:5.1.0
    ports:
      - "${YENTE_PORT}:8000"
    environment:
      - YENTE_TITLE=${YENTE_TITLE}
      # "default" the full OpenSanctions dataset
      # "us_ofac_sdn" the US main sanctions list
      - YENTE_MANIFEST=${YENTE_MANIFEST}
      # Use local Elasticsearch instance (local)
      - YENTE_ELASTICSEARCH_URL=http://elasticsearch:9200
      # Automatic data update on startup
      - YENTE_UPDATE_DATA=${YENTE_UPDATE_DATA}     
    volumes:
      # Saving downloaded data to disk
      - yente_data:/data
      # Mounting the manifest file
      - ./manifest.yml:/manifest.yml
    depends_on:
      elasticsearch:
        condition: service_healthy # Ensure ES is healthy before starting Yente
    deploy:
      resources:
        limits:
          memory: 4G

  # Data Base for Yente (Elasticsearch)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=${ES_DISCOVERY_TYPE}
      - xpack.security.enabled=${ES_SECURITY_ENABLED} # Disable security for simplicity
      - ES_JAVA_OPTS=${ES_JAVA_OPTS} # Limit Java to 1GB RAM
    ports:
      - "9200:9200" # Elasticsearch REST API for debugging
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G

    # Check Elasticsearch health
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 12


  # Databases
  # Database for Auth Service (Users/Organizations)
  mongo:
    image: mongo:6.0
    ports:
      - "${MONGO_PORT}:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  # Database for Core Service (Logs/History)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  yente_data:
  es_data:
  mongo_data:
  postgres_data: