version: '3.8'

services:
  op-adapter:
    build: ./op-adapter
    ports:
      - "3001:3000"           
    environment:
      - YENTE_API_URL=http://yente:8000
    depends_on:
      yente:
        condition: service_started

  # OpenSanctions (Yente)
  yente:
    image: ghcr.io/opensanctions/yente:5.1.0
    ports:
      - "8000:8000"
    environment:
      - YENTE_TITLE=Local Compliance API
      # "default" the full OpenSanctions dataset
      # "us_ofac_sdn" the US main sanctions list
      - YENTE_MANIFEST=/manifest.yml
      # Use local Elasticsearch instance (local)
      - YENTE_ELASTICSEARCH_URL=http://elasticsearch:9200
      # Automatic data update on startup
      - YENTE_UPDATE_DATA=true     
    volumes:
      # Saving downloaded data to disk
      - yente_data:/data
      # Mounting the manifest file
      - ./manifest.yml:/manifest.yml
    depends_on:
      elasticsearch:
        condition: service_healthy # Ensure ES is healthy before starting Yente
    deploy:
      resources:
        limits:
          memory: 4G

  # Data Base
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity
      - ES_JAVA_OPTS=-Xms1g -Xmx1g # Limit Java to 1GB RAM
    ports:
      - "9200:9200" # Elasticsearch REST API for debugging
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G

    # Check Elasticsearch health
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  yente_data:
  es_data: