version: '3.8'

services:
  op-adapter:
    build: ./op-adapter
    ports:
      - "3001:3000"           
    environment:
      - YENTE_API_URL=http://yente:8000
    depends_on:
      - yente

  # OpenSanctions (Yente)
  yente:
    image: ghcr.io/opensanctions/yente:5.1.0
    ports:
      - "8000:8000"
    environment:
      - YENTE_TITLE=Local Compliance API
      # "default" the full OpenSanctions dataset
      # "us_ofac_sdn" the US main sanctions list
      - YENTE_SCOPE=us_ofac_sdn
      # Use local Elasticsearch instance (local)
      - YENTE_ELASTICSEARCH_URL=http://elasticsearch:9200
      # Automatic data update on startup
      - YENTE_UPDATE_DATA=true
    depends_on:
      - elasticsearch
    volumes:
      # Saving downloaded data to disk
      - yente_data:/data
    deploy:
      resources:
        limits:
          memory: 4G

  # Data Base
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity
      - ES_JAVA_OPTS=-Xms1g -Xmx1g # Limit Java to 1GB RAM
    ports:
      - "9200:9200" # Elasticsearch REST API for debugging
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  yente_data:
  es_data: